os: osx
osx_image: xcode10.2
language: swift

xcode_project: HttpUtility.xcodeproj
xcode_scheme: HttpUtility
xcode_sdk: iphonesimulator12.2
xcode_destination: platform=iOS Simulator,OS=12.2,name=iPhone X
branches:
  only:
    - master
